{\
 'Base Goldsource Shared Binaries': 0,
 'Base Goldsource Shared Content': 1,
 'Base Goldsource Shared Content Localized (deprecated)': 2,
 'Base Goldsource Low Violence': 6,
 'Half-Life High Definition Content': 96,
 'Counter-Strike': 10,
 'Counter-Strike Base Content': 11,
 'Counter-Strike French': 12,
 'Counter-Strike Italian': 13,
 'Counter-Strike German': 14,
 'Counter-Strike Spanish': 15,
 'Counter-Strike Korean (Teen)': 16,
 'Counter-Strike Simplified Chinese': 17,
 'Counter-Strike Korean (Adult)': 18,
 'Counter-Strike Traditional Chinese': 19,
 'Team Fortress Classic': 20,
 'Team Fortress Classic Base Content': 21,
 'Team Fortress Classic French': 22,
 'Team Fortress Classic Italian': 23,
 'Team Fortress Classic German': 24,
 'Team Fortress Classic Spanish': 25,
 'Day of Defeat': 30,
 'Day of Defeat Base Content': 31,
 'Day of Defeat French': 32,
 'Day of Defeat Italian': 33,
 'Day of Defeat German': 34,
 'Day of Defeat Spanish': 35,
 'Deathmatch Classic': 40,
 'Deathmatch Classic Base Content': 41,
 'Deathmatch Classic French': 42,
 'Deathmatch Classic Italian': 43,
 'Deathmatch Classic German': 44,
 'Deathmatch Classic Spanish': 45,
 'Opposing Force': 50,
 'Opposing Force Base Content': 51,
 'Opposing Force German': 52,
 'Opposing Force French': 53,
 'Opposing Force Korean': 56,
 'Ricochet': 60,
 'Ricochet Base Content': 61,
 'Ricochet French': 62,
 'Ricochet Italian': 63,
 'Ricochet German': 64,
 'Ricochet Spanish': 65,
 'Half-Life': 70,
 'Half-Life French': 72,
 'Half-Life Italian': 73,
 'Half-Life German': 74,
 'Half-Life Spanish': 75,
 'Half-Life Korean (Teen)': 76,
 'Half-Life Simplified Chinese': 77,
 'Half-Life Korean (Adult)': 78,
 'Half-Life Traditional Chinese': 79,
 'Condition Zero': 80,
 'Condition Zero Base Content': 81,
 'Condition Zero French': 82,
 'Condition Zero Italian': 83,
 'Condition Zero German': 84,
 'Condition Zero Spanish': 85,
 'Condition Zero Korean (Teen)': 86,
 'Condition Zero Simplified Chinese': 87,
 'Condition Zero Korean (Adult)': 88,
 'Condition Zero Traditional Chinese': 89,
 'Condition Zero Models': 95,
 'Counter-Strike 1.6 dedicated server': 90,
 'Condition Zero Deleted Scenes': 100,
 'Condition Zero Deleted Scenes Base Content': 101,
 'Condition Zero Deleted Scenes Models': 102,
 'Condition Zero Deleted Scenes Sounds': 103,
 'Condition Zero Deleted Scenes French': 104,
 'Condition Zero Deleted Scenes Italian': 105,
 'Condition Zero Deleted Scenes German': 106,
 'Condition Zero Deleted Scenes Spanish': 107,
 'Condition Zero Deleted Scenes Korean (Teen)': 108,
 'Condition Zero Deleted Scenes Simplified Chinese': 109,
 'Condition Zero Deleted Scenes Korean (Adult)': 110,
 'Condition Zero Deleted Scenes Traditional Chinese': 111,
 'Half-Life: Blue Shift': 130,
 'Half-Life: Blue Shift French': 131,
 'Half-Life: Blue Shift German': 132,
 'Base Source Shared':  200,
 'Source Engine 64bit (for AMD64 CPU/OS)': 201,
 'Source Init (VAC)': 202,
 'Source Shared Securom': 203,
 'Base Source Shared Materials': 206,
 'Base Source Shared Models': 207,
 'Base Source Shared Sounds': 208,
 'Source Low Violence': 209,
 'Base Source Engine 2': 212,
 'Source 2007 Binaries': 216,
 'Multiplayer OB Binaries': 217,
 'Half-Life 2': 220,
 'Half-Life 2 Base Content': 221,
 'Half-Life 2 French': 223,
 'Half-Life 2 Italian': 224,
 'Half-Life 2 German': 225,
 'Half-Life 2 Spanish': 226,
 'Half-Life 2 Simplified Chinese': 227,
 'Half-Life 2 Korean (Teen)': 228,
 'Half-Life 2 Korean (Adult)': 229,
 'Half-Life 2 Traditional Chinese': 230,
 'Half-Life 2 Japanese': 231,
 'Half-Life 2 Russian': 232,
 'Half-Life 2 Thai': 233,
 'Half-Life 2 Portuguese': 234,
 'Half-Life 2 Game Dialog': 236,
 'Counter-Strike: Source': 240,
 'Counter-Strike: Source Base Content': 241,
 'Counter-Strike: Source Shared Content': 242,
 'Counter-Strike: Source French': 243,
 'Counter-Strike: Source Italian': 244,
 'Counter-Strike: Source German': 245,
 'Counter-Strike: Source Spanish': 246,
 'Counter-Strike: Source Simplified Chinese': 247,
 'Counter-Strike: Source Korean (Teen)': 248,
 'Counter-Strike: Source Korean (Adult)': 249,
 'Counter-Strike: Source Traditional Chinese': 250,
 'Counter-Strike: Source Japanese': 251,
 'Counter-Strike: Source Russian': 252,
 'Counter-Strike: Source Thai': 253,
 'Counter-Strike: Source Beta': 260,
 'Half-Life: Source': 280,
 'Half-Life: Source Base Content': 281,
 'Half-Life: Source French': 283,
 'Half-Life: Source Italian': 284,
 'Half-Life: Source German': 285,
 'Half-Life: Source Spanish': 286,
 'Half-Life: Source Simplified Chinese': 287,
 'Half-Life: Source Korean (Teen)': 288,
 'Half-Life: Source Korean (Adult)': 289,
 'Half-Life: Source Traditional Chinese': 290,
 'Half-Life: Source Japanese': 291,
 'Half-Life: Source Russian': 292,
 'Half-Life: Source Thai': 293,
 'Day of Defeat: Source': 300,
 'Day of Defeat: Source Base Content': 301,
 'Source 2007 Shared Materials': 305,
 'Source 2007 Shared Models': 306,
 'Source 2007 Shared Sounds': 307,
 'Episodic 2007 Shared': 308,
 '|all_source_engine_paths|hl2': 312,
 'Half-Life 2: Deathmatch': 320,
 'Half-Life 2: Deathmatch': 321,
 'Half-Life 2: Lost Coast': 340,
 'Half-Life 2: Lost Coast Content': 341,
 'Half-Life 2: Lost Coast French': 342,
 'Half-Life 2: Lost Coast German': 343,
 'Half-Life 2: Lost Coast Italian': 344,
 'Half-Life 2: Lost Coast Korean (Teen)': 345,
 'Half-Life 2: Lost Coast Korean (Adult)': 346,
 'Half-Life 2: Lost Coast Russian': 347,
 'Half-Life 2: Lost Coast Simplified Chinese': 348,
 'Half-Life 2: Lost Coast Spanish': 349,
 'Half-Life 2: Lost Coast Traditional Chinese': 350,
 'Half-Life Deathmatch: Source': 360,
 'Half-Life Deathmatch: Source Client': 363,
 'Half-Life 2: Episode One': 380,
 'Half-Life 2: Episode One Content': 381,
 'Half-Life 2: Episode One Shared': 213,
 'Portal': 400,
 'Portal Content': 401,
 'Portal English': 405,
 'Half-Life 2: Episode Two': 420,
 'Half-Life 2: Episode Two Content': 421,
 'Half-Life 2: Episode Two Materials': 422,
 'Half-Life 2: Episode Two Maps': 423,
 'Half-Life 2: Episode Two English': 428,
 'Team Fortress 2': 440,
 'Team Fortress 2 Content': 441,
 'Team Fortress 2 Materials': 442,
 'Team Fortress 2 Client Content': 443,
 'Left 4 Dead': 500,
 'Left 4 Dead binaries': 501,
 'Left 4 Dead base': 502,
 'Left 4 Dead client binary': 503,
 'Left 4 Dead sound': 504,
 'Left 4 Dead 2': 550,
 'Left 4 Dead 2 Demo': 590,
 'Dota 2 Beta': 570,
 'Dota 2 Beta content': 571,
 'Dota 2 Beta client': 572,
 'Dota 2 Beta Win32 content': 573,
 'Portal 2': 620,
 'Alien Swarm': 630,
 'Alien Swarm SDK Launcher': 640,
 'Counter-Strike: Global Offensive': 730,
 'Counter Strike Global Offensive Beta Common Content': 731,
 'Counter Strike Global Offensive Beta Win32 Content': 732,
 'Left 4 Dead 2 Downloadable content': 870,
 'SiN Episodes: Emergence': 1300,
 'SiN Episodes Materials': 1301,
 'SiN Episodes Models': 1302,
 'SiN Episodes Sounds': 1303,
 'SiN Episodes Core': 1304,
 'SiN Episodes: Emergence Content': 1305,
 'SiN Episodes: Emergence German': 1306,
 'SiN Episodes: Emergence German Preload': 1307,
 'SiN Episodes: Emergence Russian': 1315,
 'SiN Episodes Arena': 1308,
 'SiN Episodes Unabridged': 1316,
 'Counter-Strike: Global Offensive': 1800,
 'Dark Messiah of Might and Magic': 2100,
 'Dark Messiah Might and Magic Multi-Player': 2130,
 'The Ship': 2400,
 'The Ship': 2401,
 'The Ship Common': 2402,
 'The Ship Shared': 2412,
 'The Ship Tutorial': 2430,
 'The Ship Tutorial Content': 2406,
 'The Ship Single Player Content': 2405,
 'Bloody Good Time': 2450,
 'Vampire The Masquerade - Bloodlines': 2600,
 'Garry\'s Mod': 4000,
 'Garry\'s Mod Content': 4001,
 'Garry\'s Mod Dedicated Server': 4020,
 'Zombie Panic! Source': 17500,
 'Age of Chivalry': 17510,
 'Synergy': 17520,
 'D.I.P.R.I.P.': 17530,
 'Eternal Silence': 17550,
 'Pirates, Vikings, & Knights II': 17570,
 'Dystopia': 17580,
 'Insurgency': 17700,
 'Nuclear Dawn': 17710,
 'Smashball': 17730,
 'Insurgency 2': 222880,
 'No More Room in Hell': 224260,
 'Contagion': 238430
 }
